services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
            - ${HOME}/.composer:/home/app/.composer
        environment:
            - APP_ENV=dev
        networks:
            - internal
    mysql8:
        image: mysql:8.0.33-debian
        container_name: mysql8
        restart: always
        environment:
            MYSQL_DATABASE: 'symfony'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - '${HOME}/mysql8/data:/var/lib/mysql'
        networks:
            - internal
networks:
    internal:
